
spring:
  application:
    name: bank-inc

datasource:
  my-connection:
    jdbc-url: jdbc:mysql://localhost:3306/app_bank_inc
    username: bankinc
    password: 54321
    maximum.pool-size: 10
    pool-name: "bank-inc"
    auto-commit: true

jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
  hibernate:
    ddl-auto: update